{ config, ... }:

{
  home.sessionVariables.CC_SWITCH_CONFIG_DIR = "${config.xdg.configHome}/cc-switch";

  xdg.configFile."cc-switch/.keep".text = "";

  xdg.configFile."cc-switch/README.md".text = ''
    CC-Switch state lives here.

    - cc-switch.db is local runtime state and should not be committed.
    - provider-env is generated by sops-nix from secrets/cc-switch.yaml.
    - Manage providers through cc-switch after the secret file is present.
  '';
}
